### ISSUE TITLE
Dizionario?

### ISSUE THREAD

**Issue by supix** [e-caliano/Labyrinth2023#10]
Non è più opportuno mappare i valori di grigio ed i relativi costi in un dizionario?

https://github.com/e-caliano/Labyrinth2023/blob/0f2ee6de58c45083def33011fe6157855b8487b6/labirinto/labirinto.py#L178

**Comment by e-caliano** [comment]
Gentile Professore, grazie per il consiglio, abbiamo modificato la mappatura dei valori di grigio e dei relativi dei costi attraverso un dizionario.
