### ISSUE TITLE
Primi suggerimenti

### ISSUE THREAD

**Issue by iannellog** [e-caliano/Labyrinth2023#2]
File Elaboration
- risoluzioneLabirinto e checkDirectory non sono metodi, ma una funzioni (correggere commento)
- commento di checkDirectory:le parole "svolgere un check per vedere le directory" forse non sono le più appropriate usare verbi più adeguati (per es. in chech non si "svolge", si "effettua" o si "esegue")

File percorso
- manca un commento che spieghi cosa fa la classe 

File labirinto
- nel costruttore non si capisce il ruolo del parametro percorso_file
- nel commento del metodo json_to_image si dice che "restituire un'immagine", ma il metodo non restituisce nulla (non c'è una frase return)
- il commento di labirinto_from_image non dice tutto (il metodo attribuisce valore anche ai campi start e end); anche qui il verbo "restituisce" non è appropriato

Questo sono solo alcune osservazioni. In generale la qualità dei commenti può essere migliorata. 
Domani non posso lavorarci, vi scrivo venerd' mattina.

**Comment by e-caliano** [comment]
Va benissimo Professore, correggiamo e miglioriamo i commenti. Stiamo ultimando il Docker. 
Grazie per la disponibilità, buona giornata.
