### ISSUE TITLE
Eccezione non catturata

### ISSUE THREAD

**Issue by iannellog** [e-caliano/Labyrinth2023#3]
Nel costruttore di Labirinto viene sollevata un'eccezione che non viene catturata per cui il programma va comunque in errore.
Se si solleva un'eccezione vuol dire che è stato identificato un possibile errore che deve essere in qualche modo gestito (anche solo teminando il programma con un messaggio che aiuti l'utente a evitarlo in seguito.

**Comment by e-caliano** [comment]
Gentile Professore, grazie per il consiglio, abbiamo implementato una correzione per la gestione dell'errore.
