### ISSUE TITLE
Situazione anomala non gestita correttamente

### ISSUE THREAD

**Issue by iannellog** [e-caliano/Labyrinth2023#4]
Nel metodo gestisci_input di Labirinto nel caso l'estensione del file non sia tra quelle gestite stampate un messaggio, ma non si fa altro. Questo genera successivamente un errore con il traceback delle chiamate. Dal momento che la situazione anomala è stata identificata va gestita e il programma va terminato "gracefully" come si diece in gergo (cioè senza mandare in errore l'interprete).

**Comment by e-caliano** [comment]
Gentile Professore, grazie per il consiglio, abbiamo attuato le migliorie.
