### ISSUE TITLE
Eliminare gli spazi quando si fa l'input del nome del file

### ISSUE THREAD

**Issue by iannellog** [e-caliano/Labyrinth2023#5]
Nella funzione risoluzioneLabirinto si acquisisce il path del file con l'istruzione input.
Se il nome del file viene trascinato sul terminale in cui si esegue il programma viene aggiunto uno spazio che manda in errore il programma perché la stringa non corrisponde più a un path legale. 
Usare una funzione (mi pare sia strip() o rstrip()) per eliminare eventiuali spazi digitati prima o dopo il path in modo da non andare in errore.

**Comment by e-caliano** [comment]
Gentile Professore, grazie per il consiglio, abbiamo risolto il problema attraverso l'utilizzo della funzione strip() come da Lei consigliatoci.
