### ISSUE TITLE
Interfaccia di funzioni e metodi

### ISSUE THREAD

**Issue by iannellog** [e-caliano/Labyrinth2023#6]
Riguardare attentamente tutte le funzioni e i metodi per accertarsi che l'interfaccia sia ben documentata nei commenti (ruolo di tutti i parametri e di eventuali valori ritornati).
Accertarsi che se una funzione o un metodo ritorna qualcosa, i valori ritornati vengano utilizzati dal chamante (se non vengono mai utilizzati dal chiamante vuol dire che i valori restituiti non servono e vanno eliminati dall'interfaccia).

**Comment by GaetanoAlbano17** [comment]
Gentile Professore, abbiamo appena corretto queste situazioni
