### ISSUE TITLE
Rappresentazione del labirinto

### ISSUE THREAD

**Issue by iannellog** [e-caliano/Labyrinth2023#7]
Nel commento iniziale della classe Labirinto manca una descrizione di come è rappresentato il labirinto attraverso il campo 'maze' introdotto nel costruttore e inizializzato come lista vuota. 
Nel commento è detto che il labirinto è rappresentato come una matrice (in realtà non proprio come una matrice, ma come una lista di liste, tutte di uguale lunghezza, il che equivale di fatto a una matrice), ma per capire le convenzioni usate per rappresentare le pareti, le posizioni attraversabili e i costi, bisogna guardare il codice e *dedurre* le convenzioni usate. 
Le convenzioni usate vengono poi sfruttate nel metodo  'trova_percorsi' della classe 'RicercaPercorso' alle righe 63-70 per determinare le celle percorribili adiacenti, ma, mancando una chiara descrizione delle convenzioni usate è faticoso ricostruire la logica complessiva.
Migliorare i commenti per rendere più agevole la comprensione del codice di 'trova_percorsi'.

**Comment by GaetanoAlbano17** [comment]
Gentile Professore, abbiamo aggiunto vari commenti e migliorato la classe RicercaPercorso e la classe Labirinto con le richieste fatte
