### ISSUE TITLE
Riformattare i commenti troppo lunghi

### ISSUE THREAD

**Issue by iannellog** [e-caliano/Labyrinth2023#8]
In vari punti, ma soprattutto nel metodo 'trova_percorsi', ci sono commmenti molto lunghi su un'unica riga.
Questo rende difficoltosa la comprensione del codice perché non si riesce a leggere tutto il commento senza far scorrere la finestra.
E' buona prassi che i commenti non siano più lunghi delle linee di codice e in ogni caso tutto il codice, di norma, dovrebbe rientrare in uno schermo 'standard', andando a capo se il caso.

**Comment by GaetanoAlbano17** [comment]
Gentile Professore, abbiamo appena risolto questo problema
