### ISSUE TITLE
Sollevare un'eccezione?

### ISSUE THREAD

**Issue by supix** [e-caliano/Labyrinth2023#9]
Non è meglio sollevare un'eccezione anziché effettuare una stampa e lasciare che l'elaborazione continui?

https://github.com/e-caliano/Labyrinth2023/blob/0f2ee6de58c45083def33011fe6157855b8487b6/labirinto/labirinto.py#L60

**Comment by e-caliano** [comment]
Gentile Professore, grazie per il consiglio, abbiamo modificato l'errore in modo tale da non avere un "Traceback", ma sollevare una eccezione.
